FROM --platform=linux/amd64 public.ecr.aws/amazonlinux/amazonlinux:2023.7.20250609.0

# Create directory and give airflow user ownership
# to the virtual environment directory
USER root
ENV PYTHON_VERSION=3.11

# Install dependencies for htslib
RUN dnf install -y mariadb105-devel
RUN dnf groupinstall -y "Development Tools" && \
    dnf install -y \
        bzip2-devel \
        curl-devel \
        libcurl-devel \
        openssl-devel \
        zlib-devel \
        xz-devel \
        libpsl-devel \
        python${PYTHON_VERSION} \
        python${PYTHON_VERSION}-pip \
        python${PYTHON_VERSION}-devel \
        pkgconfig && \
    dnf clean all

ARG LIBCURL_VERSION=8.13.0
RUN curl -L -O https://curl.se/download/curl-${LIBCURL_VERSION}.tar.gz && \
    tar -xzf curl-${LIBCURL_VERSION}.tar.gz && \
    cd curl-${LIBCURL_VERSION} && \
    ./configure --with-ssl --prefix=/usr/local && \
    make -j$(nproc) && \
    make install && \
    ldconfig && \
    cd .. && \
    rm -rf curl-${LIBCURL_VERSION} curl-${LIBCURL_VERSION}.tar.gz

# Install htslib with flag enable-s3
RUN curl -L -O https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2 && \
    tar -xvf htslib-1.21.tar.bz2 && \
    cd htslib-1.21 && \
    ./configure --enable-libcurl --enable-s3 && \
    make && \
    make install && \
    cd .. && \
    rm -rf htslib-1.21 htslib-1.21.tar.bz2


RUN python${PYTHON_VERSION} -m venv /home/airflow/.venv/radiant && \
    /home/airflow/.venv/radiant/bin/pip install wheel --no-cache-dir

RUN CYVCF2_HTSLIB_MODE=EXTERNAL /home/airflow/.venv/radiant/bin/pip wheel --no-binary cyvcf2 cyvcf2 -w /home/airflow/.venv/radiant/wheels
COPY requirements.txt /home/airflow/.venv/radiant/requirements.txt
RUN /home/airflow/.venv/radiant/bin/pip wheel -w /home/airflow/.venv/radiant/wheels -r /home/airflow/.venv/radiant/requirements.txt

