receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:8889"

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]
