apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/airflow/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 22 Jul 2025 08:47:29 EDT
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://host.docker.internal:63000
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 22 Jul 2025 08:47:29 EDT
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/airflow/.minikube/profiles/minikube/client.crt
    client-key: /home/airflow/.minikube/profiles/minikube/client.key
