from pyiceberg.schema import Schema
from pyiceberg.types import BooleanType, FloatType, IntegerType, ListType, NestedField, StringType

from radiant.tasks.iceberg.utils import merge_schemas
from radiant.tasks.vcf.snv.common import SCHEMA as COMMON_SCHEMA

SCHEMA = merge_schemas(
    COMMON_SCHEMA,
    Schema(
        NestedField(100, "part", IntegerType(), required=True),
        NestedField(101, "task_id", IntegerType(), required=True),
        NestedField(108, "quality", FloatType(), required=False),
        NestedField(109, "filter", StringType(), required=False),
        NestedField(110, "info_hotspotallele", StringType(), required=False),
        NestedField(111, "info_old_record", StringType(), required=False),
        NestedField(112, "info_baseq_rank_sum", FloatType(), required=False),
        NestedField(113, "info_excess_het", FloatType(), required=False),
        NestedField(114, "info_fs", FloatType(), required=False),
        NestedField(115, "info_ds", BooleanType(), required=False),
        NestedField(116, "info_fraction_informative_reads", FloatType(), required=False),
        NestedField(117, "info_inbreed_coeff", FloatType(), required=False),
        NestedField(118, "info_mleac", IntegerType(), required=False),
        NestedField(119, "info_mleaf", FloatType(), required=False),
        NestedField(120, "info_mq", FloatType(), required=False),
        NestedField(121, "info_mq0", FloatType(), required=False),
        NestedField(122, "info_m_qrank_sum", FloatType(), required=False),
        NestedField(123, "info_qd", FloatType(), required=False),
        NestedField(124, "info_r2_5p_bias", FloatType(), required=False),
        NestedField(125, "info_read_pos_rank_sum", FloatType(), required=False),
        NestedField(126, "info_sor", FloatType(), required=False),
        NestedField(127, "info_vqslod", FloatType(), required=False),
        NestedField(128, "info_culprit", StringType(), required=False),
        NestedField(129, "info_dp", IntegerType(), required=False),
        NestedField(130, "info_haplotype_score", FloatType(), required=False),
        NestedField(140, "tumor_seq_id", IntegerType(), required=True),
        NestedField(141, "tumor_calls", ListType(241, IntegerType()), required=False),
        NestedField(142, "tumor_dp", IntegerType(), required=False),
        NestedField(143, "tumor_gq", IntegerType(), required=False),
        NestedField(144, "tumor_has_alt", BooleanType(), required=False),
        NestedField(145, "tumor_af", FloatType(), required=False),
        NestedField(146, "tumor_zygosity", StringType(), required=False),
        NestedField(147, "tumor_ad_ref", IntegerType(), required=False),
        NestedField(148, "tumor_ad_alt", IntegerType(), required=False),
        NestedField(149, "tumor_ad_total", IntegerType(), required=False),
        NestedField(150, "tumor_ad_ratio", FloatType(), required=False),
        NestedField(151, "tumor_phased", BooleanType(), required=False),
        NestedField(152, "tumor_gt_status", StringType(), required=False),
        NestedField(160, "normal_seq_id", IntegerType(), required=True),
        NestedField(161, "normal_calls", ListType(261, IntegerType()), required=False),
        NestedField(162, "normal_dp", IntegerType(), required=False),
        NestedField(163, "normal_gq", IntegerType(), required=False),
        NestedField(164, "normal_has_alt", BooleanType(), required=False),
        NestedField(165, "normal_af", FloatType(), required=False),
        NestedField(166, "normal_zygosity", StringType(), required=False),
        NestedField(167, "normal_ad_ref", IntegerType(), required=False),
        NestedField(168, "normal_ad_alt", IntegerType(), required=False),
        NestedField(169, "normal_ad_total", IntegerType(), required=False),
        NestedField(170, "normal_ad_ratio", FloatType(), required=False),
        NestedField(171, "normal_phased", BooleanType(), required=False),
        NestedField(172, "normal_gt_status", StringType(), required=False),
    ),
)
