from pyiceberg.schema import Schema
from pyiceberg.types import BooleanType, FloatType, IntegerType, ListType, NestedField, StringType

from radiant.tasks.iceberg.utils import merge_schemas
from radiant.tasks.vcf.snv.common import SCHEMA as COMMON_SCHEMA

SCHEMA = merge_schemas(
    COMMON_SCHEMA,
    Schema(
        NestedField(500, "part", IntegerType(), required=True),
        NestedField(508, "quality", FloatType(), required=False),
        NestedField(509, "filter", StringType(), required=False),
        NestedField(510, "info_hotspotallele", StringType(), required=False),
        NestedField(511, "info_old_record", StringType(), required=False),
        NestedField(512, "info_baseq_rank_sum", FloatType(), required=False),
        NestedField(513, "info_excess_het", FloatType(), required=False),
        NestedField(514, "info_fs", FloatType(), required=False),
        NestedField(515, "info_ds", BooleanType(), required=False),
        NestedField(516, "info_fraction_informative_reads", FloatType(), required=False),
        NestedField(517, "info_inbreed_coeff", FloatType(), required=False),
        NestedField(518, "info_mleac", IntegerType(), required=False),
        NestedField(519, "info_mleaf", FloatType(), required=False),
        NestedField(520, "info_mq", FloatType(), required=False),
        NestedField(521, "info_mq0", FloatType(), required=False),
        NestedField(522, "info_m_qrank_sum", FloatType(), required=False),
        NestedField(523, "info_qd", FloatType(), required=False),
        NestedField(524, "info_r2_5p_bias", FloatType(), required=False),
        NestedField(525, "info_read_pos_rank_sum", FloatType(), required=False),
        NestedField(526, "info_sor", FloatType(), required=False),
        NestedField(527, "info_vqslod", FloatType(), required=False),
        NestedField(528, "info_culprit", StringType(), required=False),
        NestedField(529, "info_dp", IntegerType(), required=False),
        NestedField(530, "info_haplotype_score", FloatType(), required=False),
        NestedField(540, "tumor_seq_id", IntegerType(), required=True),
        NestedField(541, "tumor_calls", ListType(241, IntegerType()), required=False),
        NestedField(542, "tumor_dp", IntegerType(), required=False),
        NestedField(543, "tumor_gq", IntegerType(), required=False),
        NestedField(544, "tumor_has_alt", BooleanType(), required=False),
        NestedField(545, "tumor_af", FloatType(), required=False),
        NestedField(546, "tumor_zygosity", StringType(), required=False),
        NestedField(547, "tumor_ad_ref", IntegerType(), required=False),
        NestedField(548, "tumor_ad_alt", IntegerType(), required=False),
        NestedField(549, "tumor_ad_total", IntegerType(), required=False),
        NestedField(550, "tumor_ad_ratio", FloatType(), required=False),
        NestedField(551, "tumor_phased", BooleanType(), required=False),
        NestedField(552, "tumor_gt_status", StringType(), required=False),
        NestedField(560, "normal_seq_id", IntegerType(), required=True),
        NestedField(561, "normal_calls", ListType(261, IntegerType()), required=False),
        NestedField(562, "normal_dp", IntegerType(), required=False),
        NestedField(563, "normal_gq", IntegerType(), required=False),
        NestedField(564, "normal_has_alt", BooleanType(), required=False),
        NestedField(565, "normal_af", FloatType(), required=False),
        NestedField(566, "normal_zygosity", StringType(), required=False),
        NestedField(567, "normal_ad_ref", IntegerType(), required=False),
        NestedField(568, "normal_ad_alt", IntegerType(), required=False),
        NestedField(569, "normal_ad_total", IntegerType(), required=False),
        NestedField(570, "normal_ad_ratio", FloatType(), required=False),
        NestedField(571, "normal_phased", BooleanType(), required=False),
        NestedField(572, "normal_gt_status", StringType(), required=False),
    ),
)
