INSERT OVERWRITE {{ params.starrocks_clinvar }}
SELECT
    COALESCE(GET_VARIANT_ID(c.chromosome, c.start, c.reference, c.alternate), v.locus_id) as locus_id,
    c.chromosome,
    c.start,
    c.end,
    c.reference,
    c.alternate,
    c.interpretations,
    c.name,
    c.clin_sig,
    c.clin_sig_conflict,
    c.af_exac,
    c.clnvcso,
    c.geneinfo,
    c.clnsigincl,
    c.clnvi,
    c.clndisdb,
    c.clnrevstat,
    c.alleleid,
    c.origin,
    c.clndnincl,
    c.rs,
    c.dbvarid,
    c.af_tgp,
    c.clnvc,
    c.clnhgvs,
    c.mc,
    c.af_esp,
    c.clndisdbincl,
    c.conditions,
    c.inheritance,
    c.locus,
    c.locus_hash
FROM {{ params.iceberg_clinvar }} c
LEFT JOIN {{ params.starrocks_variant_lookup }} v ON c.locus_hash = v.locus_hash
