CREATE TABLE IF NOT EXISTS {{ params.starrocks_occurrence }} (
    part INT NOT NULL,
    seq_id INT NOT NULL,
    task_id INT NOT NULL,
    locus_id bigint(20) NOT NULL,
    ad_ratio FLOAT,
    gq INT,
    dp INT,
    ad_total INT,
    ad_ref INT,
    ad_alt INT,
    zygosity CHAR(3),
    calls ARRAY<INT>,
    quality FLOAT,
    filter VARCHAR(255),
    info_baseq_rank_sum FLOAT,
    info_excess_het FLOAT,
    info_fs FLOAT,
    info_ds BOOLEAN,
    info_fraction_informative_reads FLOAT,
    info_inbreed_coeff FLOAT,
    info_mleac INT,
    info_mleaf FLOAT,
    info_mq FLOAT,
    info_m_qrank_sum FLOAT,
    info_qd FLOAT,
    info_r2_5p_bias FLOAT,
    info_read_pos_rank_sum FLOAT,
    info_sor FLOAT,
    info_vqslod FLOAT,
    info_culprit VARCHAR(255),
    info_dp INT,
    info_haplotype_score FLOAT,
    phased BOOLEAN NOT NULL,
    parental_origin VARCHAR(10),
    father_dp INT,
    father_gq INT,
    father_ad_ref INT,
    father_ad_alt INT,
    father_ad_total INT,
    father_ad_ratio FLOAT,
    father_calls ARRAY<INT>,
    father_zygosity CHAR(3),
    mother_dp INT,
    mother_gq INT,
    mother_ad_ref INT,
    mother_ad_alt INT,
    mother_ad_total INT,
    mother_ad_ratio FLOAT,
    mother_calls ARRAY<INT>,
    mother_zygosity CHAR(3),
    transmission_mode VARCHAR(50),
    info_old_record VARCHAR(2000),
  INDEX locus_id_index (`locus_id`) USING BITMAP COMMENT ''
)
ENGINE=OLAP
DUPLICATE KEY(`part`, `seq_id`, `task_id`, `locus_id`)
PARTITION BY (`part`)
DISTRIBUTED BY HASH(`locus_id`) BUCKETS 10
PROPERTIES (
    "colocate_with" = "{{ params.colocate_query_group }}"
);