CREATE TABLE IF NOT EXISTS {{ mapping.starrocks_somatic_cnv_occurrence }} (
     part int(11) NOT NULL COMMENT "",
     seq_id int(11) NULL COMMENT "",
     task_id int(11) NOT NULL COMMENT "",
     cnv_id bigint(20) NOT NULL,
     aliquot varchar(50) NULL COMMENT "",
     chromosome varchar(20) NULL COMMENT "",
     alternate varchar(20) NULL COMMENT "",
     start int(11) NULL COMMENT "",
     end int(11) NULL COMMENT "",
     type varchar(10) NULL COMMENT "GAIN, LOSS, CNLOH or GAINLOH, resolved from the DRAGEN ID",
     length int(11) NULL COMMENT "",
     name varchar(1048576) NULL COMMENT "",
     quality FLOAT NULL COMMENT "",
     calls array<int(11)> NULL COMMENT "",
     filter varchar(255) NULL COMMENT "semicolon-joined as DRAGEN writes it",
     bc int(11) NULL COMMENT "",
     pe array<int(11)> NULL COMMENT "",
     sm FLOAT NULL COMMENT "",
     svtype varchar(20) NULL COMMENT "",
     svlen int(11) NULL COMMENT "",
     reflen int(11) NULL COMMENT "",
     ciend array<int(11)> NULL COMMENT "",
     cipos array<int(11)> NULL COMMENT "",
     phased boolean NULL COMMENT "",
     -- DRAGEN allele-specific copy number (ASCN). Absent altogether on 3.10.8 and declared-but-omitted
     -- per record on 4.2.4, so expect these to be entirely NULL on older files.
     cn int(11) NULL COMMENT "",
     cnf FLOAT NULL COMMENT "",
     cnq FLOAT NULL COMMENT "",
     mcn int(11) NULL COMMENT "",
     mcnf FLOAT NULL COMMENT "",
     mcnq FLOAT NULL COMMENT "",
     maf FLOAT NULL COMMENT "MAF=0 is the direct LOH marker, where the record carries it",
     sd FLOAT NULL COMMENT "",
     ascn_as int(11) NULL COMMENT "DRAGEN FORMAT/AS, renamed because `as` is reserved",
     cytoband array<varchar(10)> NULL COMMENT "",
     symbol array<varchar(128)> NULL COMMENT "",
     nb_genes int(11) NULL COMMENT "",
     nb_snv int(11) NULL COMMENT "",
     gnomad_af FLOAT NULL COMMENT "",
     gnomad_sc int(11) NULL COMMENT "",
     gnomad_sn int(11) NULL COMMENT "",
     gnomad_sf FLOAT NULL COMMENT "",
     gnomad_sc_hom int(11) NULL COMMENT "",
     gnomad_sc_het int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(part, seq_id, task_id, cnv_id)
PARTITION BY (part);
