INSERT OVERWRITE {{ mapping.starrocks_germline_snv_variant }}
SELECT
    v.locus_id,
    COALESCE(vf.pf_wgs, 0) as pf_wgs,
    COALESCE(vf.pf_wxs, 0) as pf_wxs,
    v.gnomad_v3_af,
    v.topmed_af,
    v.tg_af,
    COALESCE(vf.pc_wgs, 0) AS pc_wgs,
    COALESCE(vf.pn_wgs, 0) AS pn_wgs,
    COALESCE(vf.pc_wgs_affected, 0) AS pc_wgs_affected,
    COALESCE(vf.pn_wgs_affected, 0) AS pn_wgs_affected,
    COALESCE(vf.pf_wgs_affected, 0) AS pf_wgs_affected,
    COALESCE(vf.pc_wgs_not_affected, 0) AS pc_wgs_not_affected,
    COALESCE(vf.pn_wgs_not_affected, 0) AS pn_wgs_not_affected,
    COALESCE(vf.pf_wgs_not_affected, 0) AS pf_wgs_not_affected,
    COALESCE(vf.pc_wxs, 0) AS pc_wxs,
    COALESCE(vf.pn_wxs, 0) AS pn_wxs,
    COALESCE(vf.pc_wxs_affected, 0) AS pc_wxs_affected,
    COALESCE(vf.pn_wxs_affected, 0) AS pn_wxs_affected,
    COALESCE(vf.pf_wxs_affected, 0) AS pf_wxs_affected,
    COALESCE(vf.pc_wxs_not_affected, 0) AS pc_wxs_not_affected,
    COALESCE(vf.pn_wxs_not_affected, 0) AS pn_wxs_not_affected,
    COALESCE(vf.pf_wxs_not_affected, 0) AS pf_wxs_not_affected,
    v.chromosome,
    v.start,
    v.end,
    v.clinvar_name,
    v.variant_class,
    v.clinvar_interpretation,
    v.symbol,
    v.impact_score,
    v.consequences,
    v.vep_impact,
    v.is_mane_select,
    v.is_mane_plus,
    v.is_canonical,
    v.rsnumber,
    v.reference,
    v.alternate,
    v.mane_select,
    v.hgvsg,
    v.hgvsc,
    v.hgvsp,
    v.locus,
    v.dna_change,
    v.aa_change,
    v.transcript_id,
    v.omim_inheritance_code
FROM {{ mapping.starrocks_germline_snv_staging_variant }} v
LEFT JOIN {{ mapping.starrocks_germline_snv_variant_frequency }} vf ON vf.locus_id = v.locus_id
