-- FIXME This query is just a filler for now. We need to differentiate between 'tumor' and 'normal' histology
-- INSERT /*+set_var(dynamic_overwrite = true)*/ OVERWRITE {{ mapping.starrocks_somatic_snv_staging_variant_frequency }}
-- WITH
-- 	somatic_sequencings AS
-- 		SELECT * FROM
-- 		FROM {{ mapping.starrocks_staging_sequencing_experiment }} s
--         WHERE s.analysis_type = 'somatic' AND s.seq_id in (select seq_id from  {{ mapping.starrocks_somatic_snv_occurrence }} where part = %(part)s)),
-- 	patients_total_count
--          AS (SELECT COUNT(DISTINCT CASE WHEN s.experimental_strategy = 'wgs' then s.patient_id end) AS cnt_wgs,
--                     COUNT(DISTINCT CASE WHEN s.experimental_strategy = 'wxs' then s.patient_id end) AS cnt_wxs,
--              FROM somatic_sequencings s
--      freqs as (SELECT o.part,
--                       o.locus_id,
--                       COUNT(distinct CASE WHEN s.experimental_strategy = 'wgs' then patient_id end) AS pc_wgs,
--                       COUNT(distinct CASE WHEN s.experimental_strategy = 'wxs' then patient_id end) AS pc_wxs,
--                FROM  {{ mapping.starrocks_somatic_snv_occurrence }} o
--                         JOIN {{ mapping.starrocks_staging_sequencing_experiment }} s ON s.seq_id = o.seq_id
--                WHERE o.part = %(part)s
--                  AND o.gq >= 20 AND o.filter='PASS' AND o.ad_alt > 3
--                GROUP BY locus_id, o.part)
-- SELECT part,
--        locus_id,
--        pc_wgs AS pc_tn_wgs,
--        (SELECT cnt_wgs FROM patients_total_count)                 AS pn_tn_wgs,
--        (DIVIDE(pc_tn_wgs / pn_tn_wgs)) AS pf_tn_wgs,
--        pc_tn_wxs,
--        (SELECT cnt_wxs FROM patients_total_count)                 AS pn_tn_wxs,
--        (DIVIDE(pc_tn_wxs / pn_tn_wxs)) AS pf_tn_wxs,
-- from freqs