INSERT OVERWRITE {{ params.starrocks_variant }}
SELECT
    v.locus_id,
    vf.pf_wgs as pf_wgs,
    vf.pf_wxs as pf_wxs,
    v.gnomad_v3_af,
    v.topmed_af,
    v.tg_af,
    vf.pc_wgs AS pc_wgs,
    vf.pn_wgs AS pn_wgs,
    vf.pc_wgs_affected AS pc_wgs_affected,
    vf.pc_wgs_affected AS pc_wgs_affected,
    vf.pf_wgs_affected AS pf_wgs_affected,
    vf.pc_wgs_not_affected AS pc_wgs_not_affected,
    vf.pc_wgs_not_affected AS pc_wgs_not_affected,
    vf.pf_wgs_not_affected AS pf_wgs_not_affected,
    vf.pc_wxs AS pc_wxs,
    vf.pn_wxs AS pn_wxs,
    vf.pc_wxs_affected AS pc_wxs_affected,
    vf.pc_wxs_affected AS pc_wxs_affected,
    vf.pf_wxs_affected AS pf_wxs_affected,
    vf.pc_wxs_not_affected AS pc_wxs_not_affected,
    vf.pc_wxs_not_affected AS pc_wxs_not_affected,
    vf.pf_wxs_not_affected AS pf_wxs_not_affected,
    v.chromosome,
    v.start,
    v.end,
    v.clinvar_name,
    v.variant_class,
    v.clinvar_interpretation,
    v.symbol,
    v.impact_score,
    v.consequences,
    v.vep_impact,
    v.is_mane_select,
    v.is_mane_plus,
    v.is_canonical,
    v.rsnumber,
    v.reference,
    v.alternate,
    v.mane_select,
    v.hgvsg,
    v.hgvsc,
    v.hgvsp,
    v.locus,
    v.dna_change,
    v.aa_change,
    v.transcript_id,
    v.omim_inheritance_code
FROM {{ params.starrocks_staging_variant }} v
JOIN {{ params.starrocks_variant_frequency }} vf ON vf.locus_id = v.locus_id
