INSERT OVERWRITE {{ params.starrocks_variants }}
SELECT
    v.locus_id,
    vf.pf as pf,
    v.gnomad_v3_af,
    v.topmed_af,
    v.tg_af,
    vf.pc AS pc,
    vf.pn AS pn,
    v.chromosome,
    v.start,
    v.end,
    v.clinvar_name,
    v.variant_class,
    v.clinvar_interpretation,
    v.symbol,
    v.impact_score,
    v.consequences,
    v.vep_impact,
    v.is_mane_select,
    v.is_mane_plus,
    v.is_canonical,
    v.rsnumber,
    v.reference,
    v.alternate,
    v.mane_select,
    v.hgvsg,
    v.hgvsc,
    v.hgvsp,
    v.locus,
    v.dna_change,
    v.aa_change,
    v.transcript_id,
    v.omim_inheritance_code
FROM {{ params.starrocks_staging_variants }} v
JOIN {{ params.starrocks_variants_frequencies }} vf ON vf.locus_id = v.locus_id
