-- Value Sets ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "sex"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "observation_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "case_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "case_analysis_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "status"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "priority"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "experimental_strategy"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "platform"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "family_relationship"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "obs_interpretation"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "sample_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "sample_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "histology_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "affected_status"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "data_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "observation"
(
    "code"     TEXT PRIMARY KEY,
    "name_en"  TEXT NOT NULL,
    "category" TEXT NOT NULL REFERENCES "observation_category" ("code")
);

CREATE TABLE IF NOT EXISTS "onset"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "data_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "file_format"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "task_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "organization_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "panel_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS life_status
(
    code    TEXT PRIMARY KEY,
    name_en TEXT NOT NULL
);

-- Patients ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "organization"
(
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"          TEXT NOT NULL UNIQUE,
    "name"          TEXT NOT NULL,
    "category_code" TEXT NOT NULL REFERENCES "organization_category" ("code")
);

CREATE TABLE IF NOT EXISTS "patient"
(
    "id"                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_patient_id"       TEXT,
    "organization_patient_id_type"  TEXT,
    "organization_id"               INTEGER REFERENCES "organization" ("id"),
    "sex_code"                      TEXT NOT NULL REFERENCES "sex" ("code"),
    "date_of_birth"                 DATE,
    "life_status_code"              TEXT NOT NULL REFERENCES life_status (code),
    "first_name"                    TEXT,
    "last_name"                     TEXT,
    "jhn"                           TEXT,
    CONSTRAINT unique_mrn_org UNIQUE ("organization_patient_id", "organization_id")
);
-- Cases ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "request"
(
    "id"                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "priority_code"            TEXT      NOT NULL REFERENCES "priority" ("code"),
    "ordering_physician"       TEXT,
    "ordering_organization_id" INTEGER REFERENCES "organization" ("id"),
    "order_number"             TEXT
);

CREATE INDEX IF NOT EXISTS idx_request_priority ON "request" ("priority_code");


CREATE TABLE IF NOT EXISTS "project"
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"        TEXT NOT NULL UNIQUE,
    "name"        TEXT NOT NULL,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS "panel"
(
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"      TEXT NOT NULL UNIQUE,
    "name"      TEXT NOT NULL,
    "type_code" TEXT NOT NULL REFERENCES "panel_type" ("code")
);

CREATE TABLE IF NOT EXISTS "case_analysis"
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"        TEXT NOT NULL UNIQUE,
    "name"        TEXT NOT NULL,
    "type_code"   TEXT NOT NULL REFERENCES "case_analysis_type" ("code"),
    "panel_id"    INTEGER REFERENCES "panel" ("id"),
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS "cases"
(
    "id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "proband_id"        INTEGER REFERENCES "patient" ("id")   NOT NULL,
    "project_id"        INTEGER REFERENCES "project" ("id")   NOT NULL,
    "case_analysis_id"  INTEGER REFERENCES "case_analysis" ("id"),
    "status_code"       TEXT NOT NULL REFERENCES "status" ("code"),
    "request_id"        INTEGER REFERENCES "request" ("id"),
    "performer_lab_id"  INTEGER REFERENCES "organization" ("id"),
    "primary_condition" TEXT,
    "note"              TEXT,
    "created_on"        TIMESTAMP NOT NULL,
    "updated_on"        TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_case_proband_id ON "cases" ("proband_id");
CREATE INDEX IF NOT EXISTS idx_case_project_id ON "cases" ("project_id");
CREATE INDEX IF NOT EXISTS idx_case_case_analysis_id ON "cases" ("case_analysis_id");
CREATE INDEX IF NOT EXISTS idx_case_status ON "cases" ("status_code");
CREATE INDEX IF NOT EXISTS idx_case_primary_condition ON "cases" ("primary_condition");
CREATE INDEX IF NOT EXISTS idx_case_created_on ON "cases" ("created_on");


CREATE TABLE IF NOT EXISTS "family"
(
    "id"                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"                       INTEGER REFERENCES "cases" ("id")    NOT NULL,
    "family_member_id"              INTEGER REFERENCES "patient" ("id") NOT NULL,
    "relationship_to_proband_code"  TEXT                                NOT NULL REFERENCES "family_relationship" ("code"),
    "affected_status_code"          TEXT                                NOT NULL REFERENCES "affected_status" ("code")
);

CREATE INDEX IF NOT EXISTS idx_family_case_id ON "family" ("case_id");

--Observations ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "observation_coding"
(
    "id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"               INTEGER REFERENCES "cases" ("id")        NOT NULL,
    "patient_id"            INTEGER REFERENCES "patient" ("id")     NOT NULL,
    "observation_code"      TEXT REFERENCES "observation" ("code") NOT NULL,
    "coding_system"         TEXT                                    NOT NULL,
    "code_value"            TEXT                                    NOT NULL,
    "onset_code"            TEXT REFERENCES "onset" ("code")       NOT NULL,
    "interpretation_code"   TEXT REFERENCES "obs_interpretation" ("code"),
    "note"                  TEXT
);

CREATE INDEX IF NOT EXISTS idx_observation_case_id ON "observation_coding" ("case_id");
CREATE INDEX IF NOT EXISTS idx_observation_patient_id ON "observation_coding" ("patient_id");

-- samples & sequencing ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "sample"
(
    "id"                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category_code"           TEXT NOT NULL REFERENCES "sample_category" ("code"),
    "type_code"               TEXT NOT NULL REFERENCES "sample_type" ("code"),
    "parent_sample_id"        INTEGER REFERENCES "sample" ("id"),
    "tissue_site"             TEXT,
    "histology_code"           TEXT REFERENCES "histology_type" ("code"),
    "submitter_sample_id"     TEXT
);

CREATE INDEX IF NOT EXISTS idx_sample_parent_id ON "sample" ("parent_sample_id");

-- Do sequencing_experiment changes
CREATE TABLE "experiment"
(
    "id"                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"                       TEXT NOT NULL UNIQUE,
    "name"                       TEXT NOT NULL,
    "experimental_strategy_code" TEXT NOT NULL REFERENCES "experimental_strategy" ("code"),
    "platform_code"              TEXT NOT NULL REFERENCES "platform" ("code"),
    "description"                TEXT
);

CREATE TABLE IF NOT EXISTS "sequencing_experiment"
(
    "id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"               INTEGER REFERENCES "cases" ("id")    NOT NULL,
    "patient_id"            INTEGER REFERENCES "patient" ("id") NOT NULL,
    "sample_id"             INTEGER REFERENCES "sample" ("id")  NOT NULL,
    "experiment_id"         INTEGER REFERENCES "experiment" ("id"),
    "status_code"           TEXT                                NOT NULL REFERENCES "status" ("code"),
    "aliquot"               TEXT                                NOT NULL,
    "request_id"            INTEGER REFERENCES "request" ("id"),
    "performer_lab_id"      INTEGER REFERENCES "organization" ("id"),
    "run_name"              TEXT,
    "run_alias"             TEXT,
    "run_date"              date,
    "capture_kit"           TEXT,
    "is_paired_end"         BOOLEAN,
    "read_length"           INTEGER,
    "created_on"            TIMESTAMP                           NOT NULL,
    "updated_on"            TIMESTAMP                           NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sequencing_experiment_case_id ON "sequencing_experiment" ("case_id");
CREATE INDEX IF NOT EXISTS idx_sequencing_experiment_patient_id ON "sequencing_experiment" ("patient_id");
CREATE INDEX IF NOT EXISTS idx_sequencing_experiment_aliquot ON "sequencing_experiment" ("aliquot");


CREATE TABLE "panel_has_genes"
(
    "panel_id"   INTEGER NOT NULL REFERENCES "panel" ("id"),
    "ensembl_id" TEXT    NOT NULL,
    "symbol"     TEXT    NOT NULL,
    PRIMARY KEY ("panel_id", "ensembl_id")
);



-- Tasks and Documents -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "pipeline"
(
    "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "description"  TEXT,
    "genome_build" TEXT
);

CREATE TABLE IF NOT EXISTS "task"
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type_code"   TEXT REFERENCES "task_type" ("code") NOT NULL,
    "pipeline_id" INTEGER REFERENCES "pipeline" ("id")  NOT NULL,
    "created_on"  TIMESTAMP                             NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_task_type ON "task" ("type_code");

CREATE TABLE IF NOT EXISTS "task_has_sequencing_experiment"
(
    "task_id"                  INTEGER REFERENCES "task" ("id")                  NOT NULL,
    "sequencing_experiment_id" INTEGER REFERENCES "sequencing_experiment" ("id") NOT NULL,
    PRIMARY KEY ("task_id", "sequencing_experiment_id")
);

CREATE TABLE IF NOT EXISTS "task_has_related_task"
(
    "task_id"         INTEGER REFERENCES "task" ("id") NOT NULL,
    "related_task_id" INTEGER REFERENCES "task" ("id") NOT NULL,
    PRIMARY KEY ("task_id", "related_task_id")
);


CREATE TABLE IF NOT EXISTS "document"
(
    "id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"                  TEXT                                    NOT NULL,
    "data_category_code"    TEXT                                    NOT NULL REFERENCES "data_category" ("code"),
    "data_type_code"        TEXT REFERENCES "data_type" ("code")   NOT NULL,
    "format_code"           TEXT REFERENCES "file_format" ("code") NOT NULL,
    "size"                  BIGINT                                  NOT NULL,
    "url"                   TEXT                                    NOT NULL,
    "hash"                  TEXT
);
CREATE INDEX IF NOT EXISTS idx_document_name ON "document" ("name");
CREATE INDEX IF NOT EXISTS idx_document_data_type_code ON "document" ("data_type_code");
CREATE INDEX IF NOT EXISTS idx_document_format_code ON "document" ("format_code");

CREATE TABLE IF NOT EXISTS "task_has_document"
(
    "task_id"     INTEGER REFERENCES "task" ("id")     NOT NULL,
    "document_id" INTEGER REFERENCES "document" ("id") NOT NULL,
    PRIMARY KEY ("task_id", "document_id")
);

CREATE TABLE IF NOT EXISTS document_has_patient
(
    document_id INTEGER NOT NULL CONSTRAINT document_has_patients_document_id_fkey REFERENCES document,
    patient_id  INTEGER NOT NULL CONSTRAINT document_has_patients_patient_id_fkey REFERENCES patient,
    CONSTRAINT document_has_patients_pkey PRIMARY KEY (document_id, patient_id)
);
-- Value Sets initial values -------------------------------------

INSERT INTO "observation_category" ("code", "name_en")
VALUES ('social_history', 'Social History'),
       ('vital_sign', 'Vital Sign'),
       ('imaging', 'Imaging'),
       ('laboratory', 'Laboratory'),
       ('procedure', 'Procedure'),
       ('survey', 'Survey'),
       ('exam', 'Exam'),
       ('therapy', 'Therapy'),
       ('activity', 'Activity')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "observation" ("code", "name_en", "category")
VALUES ('phenotype', 'Clinical sign', 'exam'),
       ('condition', 'Condition', 'exam'),
       ('ethnicity', 'Ethnicity', 'social_history')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "onset" ("code", "name_en")
VALUES ('unknown', 'Unknown'),
       ('antenatal', 'Antenatal'),
       ('congenital', 'Congenital'),
       ('neonatal', 'Neonatal (< 28 days)'),
       ('infantile', 'Infantile (>= 28 days and < 1 year)'),
       ('childhood', 'Childhood (>= 1 year and < 5 years)'),
       ('juvenile', 'Juvenile (>= 5 years and < 16 years)'),
       ('young_adult', 'Young Adult (>= 16 years and < 40 years)'),
       ('middle_age', 'Middle Age (>= 40 years and < 60 years)'),
       ('senior', 'Senior (>= 60 years)')
ON CONFLICT (code) DO NOTHING;


INSERT INTO data_type (code, name_en)
VALUES ('alignment', 'Aligned Reads'),
       ('snv', 'Germline SNV'),
       ('ssnv', 'Somatic SNV'),
       ('gcnv', 'Germline CNV'),
       ('scnv', 'Somatic CNV'),
       ('gsv', 'Germline SV'),
       ('ssv', 'Somatic SV'),
       ('somfu', 'Somatic Fusion Dragen VCF'),
       ('ssup', 'Sequencing Data Supplement'),
       ('igv', 'IGV Track'),
       ('cnvvis', 'CNV Visualization'),
       ('exp', 'Expression PNG'),
       ('covgene', 'Coverage by Gene Report'),
       ('qcrun', 'Sequencing Run QC Report'),
       ('exomiser', 'Exomiser Report')
ON CONFLICT (code) DO NOTHING;

INSERT INTO file_format (code, name_en)
VALUES ('cram', 'CRAM File'),
       ('crai', 'CRAI Index File'),
       ('vcf', 'VCF File'),
       ('gvcf', 'GVCF File'),
       ('tbi', 'TBI Index File'),
       ('tgz', 'TGZ Archive File'),
       ('json', 'JSON File'),
       ('html', 'HTML File'),
       ('tsv', 'TSV File'),
       ('bw', 'BW File'),
       ('bed', 'BED File'),
       ('png', 'PNG File'),
       ('csv', 'CSV File'),
       ('pdf', 'PDF File'),
       ('txt', 'Text File')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "organization_category" ("code", "name_en")
VALUES ('diagnostic_laboratory', 'Diagnostic Laboratory'),
       ('healthcare_provider', 'Healthcare Provider'),
       ('research_institute', 'Research Institute'),
       ('sequencing_center', 'Sequencing Center')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "sex" ("code", "name_en")
VALUES ('male', 'Male'),
       ('female', 'Female'),
       ('unknown', 'Unknown')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "case_type" ("code", "name_en")
VALUES ('heriditary_single', 'Hereditary Disease - Single Case'),
       ('heriditary_family', 'Hereditary Disease - Family Case'),
       ('tumor', 'Tumor Case')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "status" ("code", "name_en")
VALUES ('unknown', 'Unknown'),
       ('draft', 'Draft'),
       ('in_progress', 'In Progress'),
       ('revoke', 'Revoke'),
       ('completed', 'Completed'),
       ('on-hold', 'On-hold'),
       ('incomplete', 'Incomplete'),
       ('submitted', 'Submitted')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "priority" ("code", "name_en")
VALUES ('routine', 'Routine'),
       ('urgent', 'Urgent'),
       ('asap', 'Asap'),
       ('stat', 'Stat')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "experimental_strategy" ("code", "name_en")
VALUES ('wgs', 'Whole Genome Sequencing'),
       ('wxs', 'Whole Exome Sequencing'),
       ('wts', 'Whole Transcriptome Sequencing')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "platform" ("code", "name_en")
VALUES ('illumina', 'Illumina'),
       ('pacbio', 'Pacbio'),
       ('nanopore', 'Nanopore')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "family_relationship" ("code", "name_en")
VALUES ('mother', 'Mother'),
       ('father', 'Father'),
       ('proband', 'Proband'),
       ('brother', 'Brother'),
       ('sister', 'Sister')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "obs_interpretation" ("code", "name_en")
VALUES ('positive', 'Positive'),
       ('negative', 'Negative')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "sample_category" ("code", "name_en")
VALUES ('specimen', 'Specimen'),
       ('sample', 'Sample')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "sample_type" ("code", "name_en")
VALUES ('dna', 'Dna'),
       ('rna', 'Rna'),
       ('blood', 'Blood'),
       ('solid_tissue', 'Solid Tissue')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "histology_type" ("code", "name_en")
VALUES ('tumoral', 'Tumoral'),
       ('normal', 'Normal')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "affected_status" ("code", "name_en")
VALUES ('affected', 'Affected'),
       ('non_affected', 'Non Affected'),
       ('unknown', 'Unknown')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "data_category" ("code", "name_en")
VALUES ('clinical', 'Clinical'),
       ('genomic', 'Genomic')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "task_type" ("code", "name_en")
VALUES ('neba', 'Normal Exome Bioinformatic Analysis'),
       ('trba', 'Transcriptome Bioinformatic Analysis'),
       ('teba', 'Tumoral Exome Bioinformatic Analysis'),
       ('tneba', 'Tumor-Normal Exomes Bioinformatic Analysis'),
       ('ngba', 'Normal Genome Bioinformatic Analysis')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "panel_type" ("code", "name_en")
VALUES ('virtual', 'Virtual'),
       ('physical', 'Physical')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "case_analysis_type" ("code", "name_en")
VALUES ('germline', 'Germline'),
       ('somatic', 'Somatic')
ON CONFLICT (code) DO NOTHING;

INSERT INTO life_status(code, name_en) VALUES
    ('alive', 'Alive'),
    ('deceased', 'Deceased'),
    ('unknown', 'Unknown')
ON CONFLICT (code) DO NOTHING;