-- Value Sets ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "sex"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "case_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "case_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "status"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "priority"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "experimental_strategy"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "platform"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "family_relationship"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "obs_interpretation"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "sample_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "histology_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "affected_status"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "data_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "observation"
(
    "code"     TEXT PRIMARY KEY,
    "name_en"  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "onset"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "data_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "file_format"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "task_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "organization_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "panel_type"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "life_status"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "consanguinity"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "case_category"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "resolution_status"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "sequencing_read_technology"
(
    "code"    TEXT PRIMARY KEY,
    "name_en" TEXT NOT NULL
);

-- Patients ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "organization"
(
    "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"          TEXT NOT NULL UNIQUE,
    "name"          TEXT NOT NULL,
    "category_code" TEXT NOT NULL REFERENCES "organization_category" ("code")
);

CREATE TABLE IF NOT EXISTS "patient"
(
    "id"                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "organization_patient_id"       TEXT,
    "organization_patient_id_type"  TEXT,
    "organization_id"               INTEGER REFERENCES "organization" ("id"),
    "sex_code"                      TEXT NOT NULL REFERENCES "sex" ("code"),
    "date_of_birth"                 DATE,
    "life_status_code"              TEXT NOT NULL REFERENCES life_status (code),
    "first_name"                    TEXT,
    "last_name"                     TEXT,
    "jhn"                           TEXT,
    CONSTRAINT unique_mrn_org UNIQUE ("organization_patient_id", "organization_id")
);
-- Cases ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "project"
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"        TEXT NOT NULL UNIQUE,
    "name"        TEXT NOT NULL,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS "panel"
(
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"      TEXT NOT NULL UNIQUE,
    "name"      TEXT NOT NULL,
    "type_code" TEXT NOT NULL REFERENCES "panel_type" ("code")
);

CREATE TABLE IF NOT EXISTS "analysis_catalog"
(
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code"        TEXT NOT NULL UNIQUE,
    "name"        TEXT NOT NULL,
    "panel_id"    INTEGER REFERENCES "panel" ("id"),
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS "cases"
(
    "id"                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "proband_id"                INTEGER REFERENCES "patient" ("id")   NOT NULL,
    "project_id"                INTEGER REFERENCES "project" ("id")   NOT NULL,
    "analysis_catalog_id"       INTEGER REFERENCES "analysis_catalog" ("id"),
    "status_code"               TEXT NOT NULL REFERENCES "status" ("code"),
    "diagnosis_lab_id"          INTEGER REFERENCES "organization" ("id"),
    "primary_condition"         TEXT,
    "note"                      TEXT,
    "created_on"                TIMESTAMP NOT NULL,
    "updated_on"                TIMESTAMP NOT NULL,
    "priority_code"             TEXT REFERENCES "priority" ("code"),
    "case_type_code"            TEXT REFERENCES "case_type"("code"),
    "case_category_code"        TEXT REFERENCES "case_category"("code"),
    "condition_code_system"     TEXT,
    "resolution_status_code"    TEXT REFERENCES "resolution_status"("code"),
    "ordering_physician"        TEXT,
    "ordering_organization_id"  INTEGER REFERENCES "organization" ("id")
);

CREATE INDEX IF NOT EXISTS idx_case_proband_id ON "cases" ("proband_id");
CREATE INDEX IF NOT EXISTS idx_case_project_id ON "cases" ("project_id");
CREATE INDEX IF NOT EXISTS idx_case_analysis_catalog_id ON "cases" ("analysis_catalog_id");
CREATE INDEX IF NOT EXISTS idx_case_status ON "cases" ("status_code");
CREATE INDEX IF NOT EXISTS idx_case_primary_condition ON "cases" ("primary_condition");
CREATE INDEX IF NOT EXISTS idx_case_created_on ON "cases" ("created_on");


CREATE TABLE IF NOT EXISTS "family"
(
    "id"                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"                       INTEGER REFERENCES "cases" ("id")    NOT NULL,
    "family_member_id"              INTEGER REFERENCES "patient" ("id") NOT NULL,
    "relationship_to_proband_code"  TEXT                                NOT NULL REFERENCES "family_relationship" ("code"),
    "affected_status_code"          TEXT                                NOT NULL REFERENCES "affected_status" ("code")
);

CREATE INDEX IF NOT EXISTS idx_family_case_id ON "family" ("case_id");

CREATE TABLE IF NOT EXISTS "family_history"
(
    "id"                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"              INTEGER                                    NOT NULL REFERENCES "cases" ("id"),
    "patient_id"           INTEGER                                    NOT NULL REFERENCES "patient" ("id"),
    "family_member_code"   TEXT NOT NULL,
    "condition"            TEXT NOT NULL
);

--Observations ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "obs_categorical"
(
    "id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"               INTEGER REFERENCES "cases" ("id")        NOT NULL,
    "patient_id"            INTEGER REFERENCES "patient" ("id")     NOT NULL,
    "observation_code"      TEXT REFERENCES "observation" ("code") NOT NULL,
    "coding_system"         TEXT                                    NOT NULL,
    "code_value"            TEXT                                    NOT NULL,
    "onset_code"            TEXT REFERENCES "onset" ("code"),
    "interpretation_code"   TEXT REFERENCES "obs_interpretation" ("code"),
    "note"                  TEXT
);

CREATE INDEX IF NOT EXISTS idx_observation_case_id ON "obs_categorical" ("case_id");
CREATE INDEX IF NOT EXISTS idx_observation_patient_id ON "obs_categorical" ("patient_id");

CREATE TABLE IF NOT EXISTS "obs_string"
(
    "id"                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "case_id"              INTEGER                                    NOT NULL REFERENCES "cases" ("id"),
    "patient_id"           INTEGER                                    NOT NULL REFERENCES "patient" ("id"),
    "observation_code"     TEXT REFERENCES "observation" ("code")   NOT NULL,
    "value"                TEXT                                    NOT NULL
);

-- samples & sequencing ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "sample"
(
    "id"                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type_code"                 TEXT NOT NULL REFERENCES "sample_type" ("code"),
    "parent_sample_id"          INTEGER REFERENCES "sample" ("id"),
    "tissue_site"               TEXT,
    "histology_code"            TEXT REFERENCES "histology_type" ("code"),
    "submitter_sample_id"       TEXT NOT NULL,
    "submitter_organization_id" INTEGER NOT NULL REFERENCES "organization" ("id"),
    "patient_id"                INTEGER NOT NULL REFERENCES "patient" ("id")
);

CREATE INDEX IF NOT EXISTS idx_sample_parent_id ON "sample" ("parent_sample_id");

CREATE TABLE IF NOT EXISTS "sequencing_experiment"
(
    "id"                                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sample_id"                         INTEGER REFERENCES "sample" ("id") NOT NULL,
    "status_code"                       TEXT NOT NULL REFERENCES "status" ("code"),
    "aliquot"                           TEXT NOT NULL,
    "sequencing_lab_id"                 INTEGER REFERENCES "organization" ("id"),
    "run_name"                          TEXT,
    "run_alias"                         TEXT,
    "run_date"                          date,
    "capture_kit"                       TEXT,
    "created_on"                        TIMESTAMP NOT NULL,
    "updated_on"                        TIMESTAMP NOT NULL,
    "experimental_strategy_code"        TEXT NOT NULL REFERENCES "experimental_strategy" ("code"),
    "sequencing_read_technology_code"   TEXT REFERENCES "sequencing_read_technology"("code"),
    "platform_code"                     TEXT NOT NULL REFERENCES "platform" ("code")
);

CREATE INDEX IF NOT EXISTS idx_sequencing_experiment_aliquot ON "sequencing_experiment" ("aliquot");

CREATE TABLE IF NOT EXISTS "case_has_sequencing_experiment"
(
    "case_id"   INTEGER NOT NULL REFERENCES "cases" ("id"),
    "sequencing_experiment_id" INTEGER NOT NULL REFERENCES "sequencing_experiment" ("id"),
    PRIMARY KEY ("case_id", "sequencing_experiment_id")
);

CREATE TABLE IF NOT EXISTS "task"
(
    "id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task_type_code"    TEXT REFERENCES "task_type" ("code") NOT NULL,
    "created_on"        TIMESTAMP                             NOT NULL,
    "pipeline_name"     TEXT,
    "pipeline_version"  TEXT NOT NULL,
    "genome_build"      TEXT
);
CREATE INDEX IF NOT EXISTS idx_task_type ON "task" ("task_type_code");

CREATE TABLE IF NOT EXISTS "task_context"
(
    "task_id"   INTEGER NOT NULL REFERENCES "task" ("id"),
    "case_id"   INTEGER,
    "sequencing_experiment_id" INTEGER NOT NULL,
    FOREIGN KEY (case_id, sequencing_experiment_id) REFERENCES case_has_sequencing_experiment (case_id, sequencing_experiment_id)
);

CREATE TABLE "panel_has_genes"
(
    "panel_id"   INTEGER NOT NULL REFERENCES "panel" ("id"),
    "ensembl_id" TEXT    NOT NULL,
    "symbol"     TEXT    NOT NULL,
    PRIMARY KEY ("panel_id", "ensembl_id")
);

-- Tasks and Documents -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "document"
(
    "id"                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"                  TEXT                                    NOT NULL,
    "data_category_code"    TEXT                                    NOT NULL REFERENCES "data_category" ("code"),
    "data_type_code"        TEXT REFERENCES "data_type" ("code")   NOT NULL,
    "format_code"           TEXT REFERENCES "file_format" ("code") NOT NULL,
    "size"                  BIGINT                                  NOT NULL,
    "url"                   TEXT                                    NOT NULL,
    "hash"                  TEXT
);
CREATE INDEX IF NOT EXISTS idx_document_name ON "document" ("name");
CREATE INDEX IF NOT EXISTS idx_document_data_type_code ON "document" ("data_type_code");
CREATE INDEX IF NOT EXISTS idx_document_format_code ON "document" ("format_code");

CREATE TABLE IF NOT EXISTS "task_has_document"
(
    "task_id"     INTEGER REFERENCES "task" ("id")     NOT NULL,
    "document_id" INTEGER REFERENCES "document" ("id") NOT NULL,
    "type"        TEXT NOT NULL,
    PRIMARY KEY ("task_id", "document_id", "type")
);

-- Value Sets initial values -------------------------------------

INSERT INTO "case_category" ("code", "name_en") VALUES
    ('prenatal', 'Prenatal'),
    ('postnatal', 'postnatal');

INSERT INTO "resolution_status" ("code", "name_en") VALUES
    ('solved', 'Solved'),
    ('unsolved', 'Unsolved'),
    ('inconclusive', 'Inconclusive');

INSERT INTO "sequencing_read_technology" ("code", "name_en") VALUES
    ('short_read', 'Short Read'),
    ('long_read', 'Long Read');

INSERT INTO "observation" ("code", "name_en")
VALUES ('phenotype', 'Clinical sign'),
       ('condition', 'Condition'),
       ('ancestry', 'Ancestry'),
       ('note', 'Clinical Note'),
       ('consanguinity', 'Consanguinity')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "onset" ("code", "name_en")
VALUES ('unknown', 'Unknown'),
       ('antenatal', 'Antenatal'),
       ('congenital', 'Congenital'),
       ('neonatal', 'Neonatal (< 28 days)'),
       ('infantile', 'Infantile (>= 28 days and < 1 year)'),
       ('childhood', 'Childhood (>= 1 year and < 5 years)'),
       ('juvenile', 'Juvenile (>= 5 years and < 16 years)'),
       ('young_adult', 'Young Adult (>= 16 years and < 40 years)'),
       ('middle_age', 'Middle Age (>= 40 years and < 60 years)'),
       ('senior', 'Senior (>= 60 years)')
ON CONFLICT (code) DO NOTHING;

INSERT INTO data_type (code, name_en)
VALUES ('alignment', 'Aligned Reads'),
       ('snv', 'Germline SNV'),
       ('ssnv', 'Somatic SNV'),
       ('gcnv', 'Germline CNV'),
       ('scnv', 'Somatic CNV'),
       ('gsv', 'Germline SV'),
       ('ssv', 'Somatic SV'),
       ('somfu', 'Somatic Fusion Dragen VCF'),
       ('ssup', 'Sequencing Data Supplement'),
       ('igv', 'IGV Track'),
       ('cnvvis', 'CNV Visualization'),
       ('exp', 'Expression PNG'),
       ('covgene', 'Coverage by Gene Report'),
       ('qcrun', 'Sequencing Run QC Report'),
       ('exomiser', 'Exomiser Report')
ON CONFLICT (code) DO NOTHING;

INSERT INTO file_format (code, name_en)
VALUES ('cram', 'CRAM File'),
       ('crai', 'CRAI Index File'),
       ('vcf', 'VCF File'),
       ('gvcf', 'GVCF File'),
       ('tbi', 'TBI Index File'),
       ('tgz', 'TGZ Archive File'),
       ('json', 'JSON File'),
       ('html', 'HTML File'),
       ('tsv', 'TSV File'),
       ('bw', 'BW File'),
       ('bed', 'BED File'),
       ('png', 'PNG File'),
       ('csv', 'CSV File'),
       ('pdf', 'PDF File'),
       ('txt', 'Text File')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "organization_category" ("code", "name_en")
VALUES ('diagnostic_laboratory', 'Diagnostic Laboratory'),
       ('healthcare_provider', 'Healthcare Provider'),
       ('research_institute', 'Research Institute'),
       ('sequencing_center', 'Sequencing Center')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "sex" ("code", "name_en")
VALUES ('male', 'Male'),
       ('female', 'Female'),
       ('unknown', 'Unknown')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "case_type" ("code", "name_en")
VALUES ('heriditary_single', 'Hereditary Disease - Single Case'),
       ('heriditary_family', 'Hereditary Disease - Family Case'),
       ('tumor', 'Tumor Case')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "status" ("code", "name_en")
VALUES ('unknown', 'Unknown'),
       ('draft', 'Draft'),
       ('in_progress', 'In Progress'),
       ('revoke', 'Revoke'),
       ('completed', 'Completed'),
       ('on-hold', 'On-hold'),
       ('incomplete', 'Incomplete'),
       ('submitted', 'Submitted')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "priority" ("code", "name_en")
VALUES ('routine', 'Routine'),
       ('urgent', 'Urgent'),
       ('asap', 'Asap'),
       ('stat', 'Stat')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "experimental_strategy" ("code", "name_en")
VALUES ('wgs', 'Whole Genome Sequencing'),
       ('wxs', 'Whole Exome Sequencing'),
       ('rnaseq', 'RNA-Seq'),
       ('targeted_dna', 'Targeted DNA Sequencing')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "platform" ("code", "name_en")
VALUES ('illumina', 'Illumina'),
       ('pacbio', 'Pacbio'),
       ('nanopore', 'Nanopore')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "family_relationship" ("code", "name_en")
VALUES ('mother', 'Mother'),
       ('father', 'Father'),
       ('proband', 'Proband'),
       ('brother', 'Brother'),
       ('sister', 'Sister')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "obs_interpretation" ("code", "name_en")
VALUES ('positive', 'Positive'),
       ('negative', 'Negative')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "sample_type" ("code", "name_en")
VALUES ('dna', 'Dna'),
       ('rna', 'Rna'),
       ('blood', 'Blood'),
       ('solid_tissue', 'Solid Tissue')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "histology_type" ("code", "name_en")
VALUES ('tumoral', 'Tumoral'),
       ('normal', 'Normal')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "affected_status" ("code", "name_en")
VALUES ('affected', 'Affected'),
       ('non_affected', 'Non Affected'),
       ('unknown', 'Unknown')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "data_category" ("code", "name_en")
VALUES ('clinical', 'Clinical'),
       ('genomic', 'Genomic')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "task_type"(code, name_en)
VALUES ('alignment', 'Genome Alignment'),
       ('alignment_germline_variant_calling', 'Genome Alignment and Germline Variant Calling'),
       ('alignment_somatic_variant_calling', 'Genome Alignment and Somatic Variant Calling'),
       ('family_variant_calling', 'Family Joint Genotyping'),
       ('somatic_variant_calling', 'Somatic Variant Calling by Tumor-Normal Paired Samples'),
       ('tumor_only_variant_calling', 'Somatic Variant Calling by Tumor-Only Sample'),
       ('radiant_germline_annotation', 'RADIANT Germline Annotation'),
       ('exomiser', 'Exomiser'),
       ('rnaseq_analysis', 'RNAseq Analysis of Transcriptome Profiling and Gene Fusion Calling')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "panel_type" ("code", "name_en")
VALUES ('virtual', 'Virtual'),
       ('physical', 'Physical')
ON CONFLICT (code) DO NOTHING;

INSERT INTO "case_type" ("code", "name_en")
VALUES ('germline', 'Germline'),
       ('somatic', 'Somatic')
ON CONFLICT (code) DO NOTHING;

INSERT INTO life_status(code, name_en) VALUES
    ('alive', 'Alive'),
    ('deceased', 'Deceased'),
    ('unknown', 'Unknown')
ON CONFLICT (code) DO NOTHING;

INSERT INTO consanguinity (code, name_en)
VALUES ('unknown', 'Unknown'),
       ('consanguinity', 'Consanguinity in family'),
       ('no_consanguinity', 'No consanguinity in family')
ON CONFLICT (code) DO NOTHING;