# This workflow builds and pushes a Docker image to GitHub Packages
# Required environment variables:
# - REGISTRY: The Docker registry to push the image to.
# - IMAGE_NAME: The name of the Docker image.
# - (Secret) GITHUB_TOKEN: A GitHub token with permissions to push to the registry
name: Build and Push Docker Image

on:
  push:
    branches: [ "**" ]  # TODO : For test purpose, change to main before merging
    tags:
      - 'v*'

jobs:
  build_and_push:
    name: Build and Push Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}} 
            type=semver,pattern={{version}}
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

          flavor: |
            latest=auto

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

