import pyarrow as pa

clinvar_schema = pa.schema(
    [
        pa.field("chromosome", pa.string()),
        pa.field("start", pa.int64()),
        pa.field("end", pa.int64()),
        pa.field("reference", pa.string()),
        pa.field("alternate", pa.string()),
        pa.field("interpretations", pa.list_(pa.string())),
        pa.field("name", pa.string()),
        pa.field("clin_sig", pa.list_(pa.string())),
        pa.field("clin_sig_conflict", pa.list_(pa.string())),
        pa.field("filters", pa.list_(pa.string())),
        pa.field("af_exac", pa.float64()),
        pa.field("clnvcso", pa.string()),
        pa.field("geneinfo", pa.string()),
        pa.field("clnsigincl", pa.list_(pa.string())),
        pa.field("oncdn", pa.list_(pa.string())),
        pa.field("clnvi", pa.list_(pa.string())),
        pa.field("clndisdb", pa.list_(pa.string())),
        pa.field("sciincl", pa.list_(pa.string())),
        pa.field("clnrevstat", pa.list_(pa.string())),
        pa.field("onc", pa.list_(pa.string())),
        pa.field("oncdnincl", pa.list_(pa.string())),
        pa.field("alleleid", pa.int32()),
        pa.field("scidisdbincl", pa.list_(pa.string())),
        pa.field("origin", pa.list_(pa.string())),
        pa.field("scidisdb", pa.list_(pa.string())),
        pa.field("clndnincl", pa.list_(pa.string())),
        pa.field("scirevstat", pa.list_(pa.string())),
        pa.field("sci", pa.list_(pa.string())),
        pa.field("rs", pa.list_(pa.string())),
        pa.field("dbvarid", pa.list_(pa.string())),
        pa.field("af_tgp", pa.float64()),
        pa.field("oncdisdb", pa.list_(pa.string())),
        pa.field("clnvc", pa.string()),
        pa.field("clnhgvs", pa.list_(pa.string())),
        pa.field("mc", pa.list_(pa.string())),
        pa.field("oncincl", pa.list_(pa.string())),
        pa.field("oncconf", pa.list_(pa.string())),
        pa.field("af_esp", pa.float64()),
        pa.field("scidn", pa.list_(pa.string())),
        pa.field("clndisdbincl", pa.list_(pa.string())),
        pa.field("scidnincl", pa.list_(pa.string())),
        pa.field("oncdisdbincl", pa.list_(pa.string())),
        pa.field("oncrevstat", pa.list_(pa.string())),
        pa.field("old_multiallelic", pa.string()),
        pa.field("conditions", pa.list_(pa.string())),
        pa.field("inheritance", pa.list_(pa.string())),
        pa.field("sciscv", pa.list_(pa.string())),
        pa.field("clnsigscv", pa.list_(pa.string())),
        pa.field("oncscv", pa.list_(pa.string())),
        pa.field("locus", pa.string()),
        pa.field("hash", pa.string()),
    ]
)
